Iter5
Pingachguk/ya-shortener pull request #5
Opened 2023-12-17 20:55 UTC by Pingachguk

- Рефакторим конфиг
- Добавляем обработку переменныз окрудения с помощью пакетф carl0s env

2023-12-18 13:57 UTC, tmvrus requested changes

2023-12-18 13:57 UTC, tmvrus commented on cmd/shortener/main.go
> +	fmt.Println(123)
что это?

2023-12-18 13:57 UTC, tmvrus commented on cmd/shortener/main.go
> +	url := urls[id]
семантика доступ к значения в map поддерживает сразу проверку на наличие данных
https://go.dev/blog/maps
"two-value assignment"

2023-12-18 13:57 UTC, tmvrus commented on cmd/shortener/main.go
> +	r.Body.Read(b)
Read может вернуть ошибку, ее нужно обрабатывать

2023-12-18 13:57 UTC, tmvrus commented on cmd/shortener/main.go
> +	res := fmt.Sprintf("%s/%s", cfg.Base, short)
это очень слабый алгоритм генерации short id

2023-12-18 13:57 UTC, tmvrus commented on cmd/shortener/main.go
> +type URLStorage map[string]string
для какой цели понадобилось создавать отдельный тип - неясно

2023-12-18 21:28 UTC, Pingachguk commented on cmd/shortener/main.go
> +	res := fmt.Sprintf("%s/%s", cfg.Base, short)
Решил использовать готовое решение: 
https://pkg.go.dev/github.com/teris-io/shortid

Алфавит: `0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-`
Длина: 9
Пример: `_BYd7idIg `

2023-12-19 09:57 UTC, tmvrus approved these changes

2024-01-08 20:58 UTC, merged

2024-01-09 12:17 UTC, tmvrus commented on cmd/shortener/main.go
> +	res := fmt.Sprintf("%s/%s", cfg.Base, short)
хороший выбор